export const SET_STATE = "SET_STATE"
export const RAIS_THE_TASK = "RAIS_THE_TASK"
export const ADD_TASK = "ADD_TASK"
export const SHOW_ADD_DIALOG = "SHOW_ADD_DIALOG"
export const HIDE_DIALOG = "HIDE_DIALOG"